### ISSUE TITLE
Status Report - Member Updates (Sep 11 - Sep 17)

### ISSUE THREAD

**Issue by edgr-sanchez** [unt-software-engineering/team-project#2]
Please copy and paste the following template text as a comment below. Replace the placeholders with your own information. 

This blog post is due every Saturday by 11:59pm. Please try to have it submitted a day early as it will take time to create the team blog post and compile all the member posts. 

```
# **Member Name:** [FIRST NAME] [LAST INITIAL]

### **Major tasks completed:**

[ENTER TEXT]

### **Tasks in progress:**

[ENTER TEXT]

### **Challenges (and if they were overcome):**

[ENTER TEXT]

### **Total Hours Spent for the week working on the project:**

[ENTER TEXT]

```

**Comment by edgr-sanchez** [comment]
**Member Name:** Clayton B.

* **Major tasks completed:**

    1. This week I created a mock up home screen in Android Studio to get an idea of what our app should look like and what kind of vibe it will have when people see it. 

    2. I made a few forum posts on a website called Linus Tech Tips to get an idea of the response/need for an app like Tastr. Overall the response was very positive, and we received a few suggestions as well - such as vegetarian options and an options that allows you to specify if the restaurants serve alcohol or not. 

    3. I also made an example java source code for grabbing images from a url, as most people in our group don't have experience in java.

* **Tasks in progress:**

    I researched and started development on the Yelp API. This is a vital part of our back end as it will allow us to find restaurants and dishes within a certain radius much more quickly than developing the entire code ourselves. I got a working example uploaded to GITHUB that searches for business with a certain name and city.

* **Challenges (and if they were overcome):**

    The yelp API is huge, and parsing the specific data we need in a reasonable amount of time will be the most difficult part of my job I think. 
Another challenge we are facing as a team is all of the new unfamiliar technology/languages we will be using. 

* **Total Hours Spent for the week working on the project:**

    10 hours

**Comment by edgr-sanchez** [comment]
**Member Name:** Joshua T

* **Major tasks completed:**

    1. Development environment setup.
    2. Began Designing program structure
    3. Assign Project Tasks
    4. Team Meetings Planned
    5. Drag example

* **Tasks in progress:**

    1. Program Structure/Design
    2. Project Planning
    3. Java/Android code research and learning

* **Challenges (and if they were overcome):**

    Relearning Java & working in Android Studio

* **Total Hours Spent for the week working on the project:**

    10 hours

**Comment by edgr-sanchez** [comment]
**Member Name:** Will F.

* **Major tasks completed:**

    1. Menus designed
    2. Learned much about Android Studio
    3. Began some menu development

* **Tasks in progress:**

    1. Menu designed
    2. Learning Java/Android Studio

* **Challenges (and if they were overcome):**

    1. Learning Java on the fly
    2. I have had an otherwise busy week. Next week will be more committed.

* **Total Hours Spent for the week working on the project:**

    2 hours

**Comment by edgr-sanchez** [comment]
**Member Name:** Brashad H.

* **Major tasks completed:**

    No major tasks completed

* **Tasks in progress:**

    Learning Android studio and Java object handling

* **Challenges (and if they were overcome):**

    Java animations (Yes, I overcame)

* **Total Hours Spent for the week working on the project:**

    5 hours

**Comment by edgr-sanchez** [comment]
**Member Name:** Edgar S.

* **Major tasks completed:**

    1. Set up GitHub organization and team repository
    2. Set up Slack team and channels
    3. Set up Android Studio and its dependencies
    4. Set up status report blog
    5. Collaborated with team members to have them join GitHub and Slack
    6. Met with team members to discuss the project and responsibilities
    7. Helped brainstorm and come up with concepts for app UI

* **Tasks in progress:**

    1. Learning my way around Android Studio
    2. Refreshing my memory with Java
    3. Learning the API for Google Firebase

* **Challenges (and if they were overcome):**

    1. Relearning Java as I haven't used it in a few years (overcome)
    2. Worked with personal friend to design logo for app (overcome)

* **Total Hours Spent for the week working on the project:**

    9 hours

**Comment by edgr-sanchez** [comment]
# Team Summary

### **Total hours spent working on the project:**

36 hours (including Clayton, Brashad, Edgar, Josh, and Will)

### **Questions or concerns for instructor/grader:**

Our 6th team member, Jimmy Perez, was assigned to our team late and he is still getting caught up on all tasks and creating online accounts.

**Comment by jimmydperez** [comment]
Member Name: Jimmy P.

Major tasks completed:

1. Joined the group and received information over project
2. set up GitHub account
3. Set up slack Account.
4. Installed Android Studio.

Tasks in progress:

1. Learning some android studio.
2. Getting caught up with group details.
3. Getting caught up with major project requirements.

Challenges (and if they were overcome):

1. Joining the group a week late.
2. learning Java.

Total Hours Spent for the week working on the project:

2 hours

**Comment by edgr-sanchez** [comment]
Blog post completed and submitted:

https://unt-software-engineering.github.io/team-project/articles/week-of-sep-11-to-sep-17
