### ISSUE TITLE
Status Report - Member Updates (Sep 18 - Sep 24)

### ISSUE THREAD

**Issue by edgr-sanchez** [unt-software-engineering/team-project#3]
Please copy and paste the following template text as a comment below. Replace the placeholders with your own information. 

This blog post is due every Saturday by 11:59pm. **Please try to have it submitted a day early as it will take time to create the team blog post and compile all the member posts.** 

```
# **Member Name:** [FIRST NAME] [LAST INITIAL]

### **Major tasks completed:**

[ENTER TEXT]

### **Tasks in progress:**

[ENTER TEXT]

### **Challenges (and if they were overcome):**

[ENTER TEXT]

### **Total Hours Spent for the week working on the project:**

[ENTER TEXT]

```

**Comment by joshtews** [comment]
# **Member Name:** Joshua Tews

### **Major tasks completed:**

Item Class Created

### **Tasks in progress:**

Item Class Completion
working on drawing and item from a class

### **Challenges (and if they were overcome):**

problems trying to make a new object with multiple elements

### **Total Hours Spent for the week working on the project:**

4

**Comment by Outofit08** [comment]
**Member Name: Brashad Hasley

Major Tasks completed:**

Created image swipe

### **Tasks in progress:**

Image swipe vertically
Porting application.

### **Challenges (and if they were overcome):**

Vertical image swiping(still working on it).

### **Total Hours Spent for the week working on the project:**

4

**Comment by Remixt** [comment]
# **Member Name:** [Clayton] [B]

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Integration of the Yelp Api in android studio.

### **Challenges (and if they were overcome):**

Finished the yelp API functions/class, but when integrating it into Android Studio the app crashes due to non - asynchronus calls. Challenge has not been over come, but I am aware of the solution.

### **Total Hours Spent for the week working on the project:**

10

**Comment by jimmydperez** [comment]
# **Member Name:** JIMMY P

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Researching how to make an image into a singular element and how to get an image within a certain border every time the image loads in the app

### **Challenges (and if they were overcome):**

Getting comfortable with Java

### **Total Hours Spent for the week working on the project:**

3

**Comment by edgr-sanchez** [comment]
# **Member Name:** Edgar S.

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Researching Google Firebase and creating a layout for our database.

### **Challenges (and if they were overcome):**

Learning how to use and implement a database on Firebase as well as figuring out what best approach to take. Other challenges were being busy all week due to tests.

### **Total Hours Spent for the week working on the project:**

4

**Comment by dafridge** [comment]
# **Member Name:** Will F.

### **Major tasks completed:**

N/a

### **Tasks in progress:**

Adding Menus

### **Challenges (and if they were overcome):**

Figuring out how to link pages in Java. No.

### **Total Hours Spent for the week working on the project:**

6

**Comment by edgr-sanchez** [comment]
All member updates added to blog post:

https://unt-software-engineering.github.io/team-project/articles/week-of-sep-11-to-sep-24
