### ISSUE TITLE
Status Report - Member Updates (Sep 25 - Oct 01)

### ISSUE THREAD

**Issue by edgr-sanchez** [unt-software-engineering/team-project#5]
Please copy and paste the following template text as a comment below. Replace the placeholders with your own information. 

This blog post is due every Saturday by 11:59pm. **Please try to have it submitted a day early as it will take time to create the team blog post and compile all the member posts.** 

```
# **Member Name:** [FIRST NAME] [LAST INITIAL]

### **Major tasks completed:**

[ENTER TEXT]

### **Tasks in progress:**

[ENTER TEXT]

### **Challenges (and if they were overcome):**

[ENTER TEXT]

### **Total Hours Spent for the week working on the project:**

[ENTER TEXT]

```

**Comment by Remixt** [comment]
# **Member Name:** [Clayton] [B]

### **Major tasks completed:**

[Fully integrated GPS and Yelp functionality]

### **Tasks in progress:**

[UI research and parsing data from yelp]

### **Challenges (and if they were overcome):**

[getting gps signal permissions, yes I overcame them.] 

### **Total Hours Spent for the week working on the project:**

[30]

**Comment by jimmydperez** [comment]
# **Member Name:** Jimmy P.

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Looking into border on images integration and more of the class elements.

### **Challenges (and if they were overcome):**

working with the application and the API to make sure they do not cause unwanted bugs.

### **Total Hours Spent for the week working on the project:**

3

**Comment by joshtews** [comment]
# **Member Name:** Joshua Tews

### **Major tasks completed:**

Got the app working on my computer again

### **Tasks in progress:**

Creating an element from the class

### **Challenges (and if they were overcome):**

making git and my android studio work

### **Total Hours Spent for the week working on the project:**

4

**Comment by edgr-sanchez** [comment]
# **Member Name:** Edgar S.

### **Major tasks completed:**

Renamed app package, added Firebase configuration to app branch.

### **Tasks in progress:**

Purchasing an Android device to test app on. Create database.

### **Challenges (and if they were overcome):**

Running app on Android Studio and running emulator, which didn't work, hence why I'm purchasing an Android device.

### **Total Hours Spent for the week working on the project:**

6

**Comment by edgr-sanchez** [comment]
Post is live:

https://unt-software-engineering.github.io/team-project/articles/week-of-sep-18-to-sep-24
