### ISSUE TITLE
Status Report - Member Updates (Oct 02 - Oct 08) 

### ISSUE THREAD

**Issue by edgr-sanchez** [unt-software-engineering/team-project#6]
Please copy and paste the following template text as a comment below. Replace the placeholders with your own information. 

This blog post is due every Saturday by 11:59pm. **Please try to have it submitted a day early as it will take time to create the team blog post and compile all the member posts.** 

```
# **Member Name:** [FIRST NAME] [LAST INITIAL]

### **Major tasks completed:**

[ENTER TEXT]

### **Tasks in progress:**

[ENTER TEXT]

### **Challenges (and if they were overcome):**

[ENTER TEXT]

### **Total Hours Spent for the week working on the project:**

[ENTER TEXT]

```

**Comment by joshtews** [comment]
# **Member Name:** Joshua Tews

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Instantiating classes as a list

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

3

**Comment by jimmydperez** [comment]
# **Member Name:** Jimmy Perez

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Finding out ways to make an image integrate with a border.

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

2

**Comment by Outofit08** [comment]
# **Member Name:** Brashad H

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Integrating new UI images to act as a background

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

2

**Comment by Remixt** [comment]
# **Member Name:** Clayton B
### **Major tasks completed:**

[Integrated main activity to allow access to all other activities within app.]

### **Tasks in progress:**

[parsing and uploading database information with asynchronous real-time updates]

### **Challenges (and if they were overcome):**

[Reducing data size to manageable chunks that android can upload. Haven't overcome yet.]

### **Total Hours Spent for the week working on the project:**

[15]

**Comment by edgr-sanchez** [comment]
# **Member Name:** Edgar S

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Firebase

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

1

**Comment by edgr-sanchez** [comment]
https://unt-software-engineering.github.io/team-project/articles/week-of-oct-02-to-oct-08
