### ISSUE TITLE
Status Report - Member Updates (Oct 09 - Oct 15)

### ISSUE THREAD

**Issue by edgr-sanchez** [unt-software-engineering/team-project#7]
Please copy and paste the following template text as a comment below. Replace the placeholders with your own information. 

This blog post is due every Saturday by 11:59pm. **Please try to have it submitted a day early as it will take time to create the team blog post and compile all the member posts.** 

```
# **Member Name:** [FIRST NAME] [LAST INITIAL]

### **Major tasks completed:**

[ENTER TEXT]

### **Tasks in progress:**

[ENTER TEXT]

### **Challenges (and if they were overcome):**

[ENTER TEXT]

### **Total Hours Spent for the week working on the project:**

[ENTER TEXT]

```

**Comment by Remixt** [comment]
# **Member Name:** Clayton B

### **Major tasks completed:**

Fully integrated automated database writing. 
Cleaned project with code formatting, and removed depreciated/inefficient processes.
Spellchecked comments and variables.
Tightened security of variables.

### **Tasks in progress:**

Reading information from database and caching images.

### **Challenges (and if they were overcome):**

Reading information from database in an efficient process and converting that to useful information in the GUI.

### **Total Hours Spent for the week working on the project:**

[10]

**Comment by joshtews** [comment]
# **Member Name:** Joshua Tews

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Class intstantiation

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

2

**Comment by Outofit08** [comment]
# **Member Name:** Brashad Hasley

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Integrating new UI elements into the swiping menu

### **Challenges (and if they were overcome):**

Getting updated branch(yes)

### **Total Hours Spent for the week working on the project:**

2

**Comment by jimmydperez** [comment]
# **Member Name:** Jimmy P.

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Working on first draft of the main page art

### **Challenges (and if they were overcome):**

N/a

### **Total Hours Spent for the week working on the project:**

2

**Comment by dafridge** [comment]
# **Member Name:** Will F.

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Getting the settings screen running.

### **Challenges (and if they were overcome):**

Getting each object in the settings screen to work (it is not entirely finished)

### **Total Hours Spent for the week working on the project:**

3

**Comment by edgr-sanchez** [comment]
# **Member Name:** Edgar S.

### **Major tasks completed:**

N/A

### **Tasks in progress:**

Contact restaurants and take photos of menu items

### **Challenges (and if they were overcome):**

N/A

### **Total Hours Spent for the week working on the project:**

1

**Comment by edgr-sanchez** [comment]
Blog post:

https://unt-software-engineering.github.io/team-project/articles/week-of-oct-09-to-oct-15
